; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Mon Sep 28 2020 13:46:17 GMT-0400 (Eastern Daylight Time)
G28 U
M561 ; clear any bed transform
G30 P0 X20 Y100 Z-99999 ; probe near a leadscrew, half way along Y axis
G30 P1 X280 Y100 Z-99999 S2 ; probe near a leadscrew and calibrate 2 motors
G90
G0 X150 F9000
;G29  ; probe the bed and enable compensation


