; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Thu Oct 29 2020 12:13:59 GMT-0400 (Eastern Daylight Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


