; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Thu Oct 29 2020 12:13:59 GMT-0400 (Eastern Daylight Time)
M280 P0 S90 ; retract BLTouch

