; tfree0.g
; called when tool 0 is freed
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Thu Oct 29 2020 12:14:00 GMT-0400 (Eastern Daylight Time)

M83          ; relative extruder movement
M106 S0      ; turn off our print cooling fan
G91          ; relative axis movement
G1 Z3 F500   ; up 3mm
G90          ; absolute axis movement
G1 S2 X-65 F6000 ; park the X carriage at -65mm